### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by pwrstudio** [commune-rideshare/commune_heaven#1]
- [x] Identifying colors for drivers/passengers/rides – also in the different states of activity (unoccupied, in transit to passenger, etc....)
- [x] Typeface? Currently work sans
- [ ] Custom mapbox style: https://www.mapbox.com/studio/styles/
- [ ] Growl-style notifications for events:

![growl-style-message-toaster-plugin-for-jquery-notify](https://cloud.githubusercontent.com/assets/8209990/15693394/398a37a6-2795-11e6-9d1c-9d42c7cba988.jpg)

**Comment by artroing** [comment]
- [ ] merging of riders/users into metaballs. more people bigger shape. 2d metaballs – through similar blurring like is there is now – should be possible. If possible, there needs to be a slight random displacement between the nodes riding together for them to form shapes and not only a big ball.
- [ ] custom sounds, maybe i can return with something that links it to the movies (although I also like the current one).
- [ ] private to communal bar in the bottom, so you can follow the transition. (of course here then a number of total shares owned by VCs should be defined). 
- [ ] Show how the shares owned by riders and drivers correspond to total value of the network. Maybe alternate between shares in numbers and in %.
- [x] commune logo in bottom right (will provide. Svg?)
- [ ] develop stalker
- [ ] is there a growth built in? Would be great if the network can gradually become bigger and more cooperatively owned.

**Comment by artroing** [comment]
I think there is a problem with the difference in colour, as it denotes hierarchy. Of course it makes sense if they are shown as two rows in the top. Will think of an solution to this asap.

Btw, this is turning out great.

**Comment by artroing** [comment]
- [ ] maybe colours can be replaced by growl style popups on location to mark the events?

**Comment by pwrstudio** [comment]
**Color**
I think there is a need for differentiation using either color or something else, to show the different states of the drivers/passengers:

Driver
- Waiting for ride
- En route to pick up
- perhaps other?

Rider 
- Waiting for pick up
- ??? 

So you can graps what is going on and not just see a bunch of circles moving around...

**Sound** 
yes, just picked a random one from freesound.org, send whatever else you would prefer if so! Sounds can of course be attached to other events too, but might be a bit messy. (now connected to completed trip)

**Logo**
Yepp, svg is good

**Metaballs**
I know this is an important part, visually. Will try to make it work. Fallback plan is to just make the dot bigger for each rider that is picked up... But will try to get the metaballs working.

**Notifications**
If you hit **cmd+alt+i** and select console you can see the events (request, pickup etc...) taking place. Will try out making this visible in the actual site, with those growl-style notifications appearing and fading out in the corner (bottom right perhaps).

**Comment by pwrstudio** [comment]
Another thing:

**Names**
These are now just generated using this:
http://chancejs.com/#name
So kind of US-centric.....

**Comment by artroing** [comment]
Color
Yes! Agreed. Will return with something on this, and then also apply to the visualizations (the reason i'm a bit struggling with this, as it has to fit for both systems)

Names
I can compile a database for local names, I think that could be great. What do you think of involving €? Both in total spent / total distributed / money earned through ownership per driver / rider.

Notifications
would be awesome

Metaballs
Yes, this is important, to see correlation between our part and the other parts of the project. 

btw
@guimachiavelli can assist if there is specific input needed that is more code-based (as I clearly lack in that department)

**Comment by guimachiavelli** [comment]
@pwrstudio: I am (very) slowly reading through the code, but let me know if there's anything you think would particularly benefit from an extra set of eyes/brain 👍

**Comment by pwrstudio** [comment]
Thanks @guimachiavelli !

A practical thing that would be great is if somebody could take a photo of the tablet in question accessing this pre-version of the site:
http://utopian-friends.surge.sh

To get an idea of the screen real estate available. 

And re:code, it is a bit of a mess, sorry gui! some parts a commented but other might be cryptic. Lots of this: http://callbackhell.com/

Main thing is that there is a object called `city` that has collections named `riders` and `drivers` that contain object representing these actors – They interact through rides being requested and drivers accepting at random-regular intervals from the app.js file.

The two core things I am working on is **multi-rider trips** and how to **show them as metaballs**. 

Two parts mentioned above, that might be possible to approach are:
- [ ] Implementing the growl-style notifications
  if you open the dev console in chrome you can see that the events such as request of ride, pick up, generate messages (handled by the log.js module) – so somehow getting these on the actual site in a way that does not take up to much space, while still giving more of a feeling of waht is going on.
- [ ] Calculating and showing shares as % of total supply. Adding a % column to the tables of drivers/riders at top. Calculating and visualizing driver vs rider ownership.

If you would like to contribute to either of those (or anything else!) I would be very grateful.    

@artroing Probably you have already sent this, but is there a text/document describing the current ideas on how the network would go from its initial (vc-funded?) state to full-coop? 

Regarding growth of the network + €conomy: yes, if all goes well, will try. But first the multi-metaballs...

**Comment by artroing** [comment]
@pwrstudio Sounds like a plan.

Regarding the shift from private to full-coop. The easiest (and also accurate) representation would be to give the VCs a large quantity of shares that than slowly are phased out through the creation of new shares by movement. The bar at the bottom would simply just have to present % distribution of shares between initial amount (VC) and shares created after that (coop).

**Comment by artroing** [comment]
We will be with the tablets tomorrow morning and will return with a photo then. 
Best

**Comment by artroing** [comment]
[commune logo.svg.zip](https://github.com/commune-rideshare/commune_heaven/files/309189/commune.logo.svg.zip)

**Comment by artroing** [comment]
@pwrstudio for the colours:
Please eplace the red with #3396ce and the background of 'joint rides' with the same colour.
