### ISSUE TITLE
Tablet videos

### ISSUE THREAD

**Issue by guimachiavelli** [commune-rideshare/commune_heaven#2]
Asus ZenPad 10 (chrome 46.0.2490.76/Android 6.0) (resolution: 1280 x 800)
https://we.tl/DeW6bdSvqu

Asus Memo Pad 7 (chrome 48.02.2564.95/Android 4.4.2) (resolution: 1024 x 600)
https://we.tl/rs64jFEIyr

ping @pwrstudio

**Comment by pwrstudio** [comment]
Thanks! 

So one of the zenpad 10 will play the heaven visualization and memopad 7 will show the stalker visualization? @artroing 

Could you try going to this site (in chrome) and see if the "launch fullscreen" button works:
https://davidwalsh.name/demo/fullscreen.php

**Comment by guimachiavelli** [comment]
I don't have the tablets with me, but I guess it should work (caniuse.com says the fullscreen api is supported behind since chrome 15). 

alternatively, perhaps using <meta name="apple-mobile-web-app-capable" content="yes">  and adding it to the home screen could work, no?

**Comment by artroing** [comment]
@pwrstudio accurate! 👍

**Comment by artroing** [comment]
We will be with the tablets tomorrow at 12:00 and then able to try out the full screen button if still needed? @pwrstudio

**Comment by guimachiavelli** [comment]
pictures of the tablets running current version of the simulation: http://imgur.com/a/bH6Ej

**Comment by artroing** [comment]
@pwrstudio Looks super good when we tried it out! But details that need some changing:
- [x] Commune logo in the corner, as it can be misstaken for just a random map simulator, with commune branding it links it to the project and makes the visitor take a seond look (which it deserves).
- [x] bigger text & bigger popups (hard to read). Change font to San Francisco.
- [x] bigger dots (I think previous size was good)
- [x] change colour on active ride dots and match joint ride column background colour. Right now using top colour scheme in movies (see attached) but could change to bottom if red is preferred. 

![image](https://cloud.githubusercontent.com/assets/9105714/15993385/ac7b6188-30e4-11e6-95fd-1eb96a8ab564.png)

**Comment by pwrstudio** [comment]
Hej! thanks a lot. I am thinking that the heaven-simulation would be better in landscape mode (and the stalker sim coming in a bit in portrait.) what do you say?

**Comment by artroing** [comment]
Ah. Yes maybe, we can try it out tomorrow! Reasoning behind heaven/portrait stalker/landscape was:
- map has more space when the top info isn't stretched out in heaven. Also the two 10" in the backseat are landscape, so it signals a different, more 'interactive' function. 
- there is a perfect place for the 7" in landscape in the car (it looks integrated into the control board).

**Comment by pwrstudio** [comment]
@artroing So the blue color would represent active rides? Sure. Could you send a color code?

**Comment by artroing** [comment]
Exactly! #3396ce
