### ISSUE TITLE
Names

### ISSUE THREAD

**Issue by guimachiavelli** [commune-rideshare/commune_heaven#4]
@pwrstudio: arthur asked me for a dutch name database. I was thinking of using this for [first names](http://www.meertens.knaw.nl/nvb/topnamen/provincie/Noord-Holland/2014) and this for [last names](http://www.dutchgenealogy.nl/tng/surnames-all.php), but I see you are using a library to generate them.

would you want me to create a quick function for that (probably _shudder_ monkey patching, given the limited time)? or is it too late now?

**Comment by guimachiavelli** [comment]
wanted to do a PR, but was having problems with a missing config.js, so I put it in a gist: https://gist.github.com/guimachiavelli/e7af2e76daceedf3151fe9e24d714e6b

ping @pwrstudio

**Comment by pwrstudio** [comment]
hej gui! sorry missed this, but added the name generator now! thanks a lot
